/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package ihmc_hands_ros2;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (ihmc_hands_ros2/AbilityHandState):
<pre>{@code
# The actuator positions in degrees
float32[6] actuator_positions

# The current finger velocities (deg/sec)
float32[6] actuator_velocities

# The actuator currents in amps
float32[6] actuator_currents

# The touch sensor pressure readings in Newtons
float32[30] touch_sensor_readings

# If grip control mode, the current grip stage
int32 grip_stage

# The goal positions in degrees
float32[6] goal_positions

# The goal or max velocities (deg/sec)
float32[6] goal_velocities
}</pre>
*/
public class AbilityHandState implements ROS2Message<AbilityHandState>
{
   public static final java.lang.String name = "ihmc_hands_ros2::msg::dds_::AbilityHandState_";

   /**
      The actuator positions in degrees
   */
   private final float[] actuator_positions_;
   /**
      The current finger velocities (deg/sec)
   */
   private final float[] actuator_velocities_;
   /**
      The actuator currents in amps
   */
   private final float[] actuator_currents_;
   /**
      The touch sensor pressure readings in Newtons
   */
   private final float[] touch_sensor_readings_;
   /**
      If grip control mode, the current grip stage
   */
   private int grip_stage_;
   /**
      The goal positions in degrees
   */
   private final float[] goal_positions_;
   /**
      The goal or max velocities (deg/sec)
   */
   private final float[] goal_velocities_;

   public AbilityHandState()
   {
      actuator_positions_ = new float[6];
      actuator_velocities_ = new float[6];
      actuator_currents_ = new float[6];
      touch_sensor_readings_ = new float[30];
      goal_positions_ = new float[6];
      goal_velocities_ = new float[6];

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += (6 * 4) + CDRBuffer.alignment(currentAlignment, (6 * 4)); // actuator_positions_
      currentAlignment += (6 * 4) + CDRBuffer.alignment(currentAlignment, (6 * 4)); // actuator_velocities_
      currentAlignment += (6 * 4) + CDRBuffer.alignment(currentAlignment, (6 * 4)); // actuator_currents_
      currentAlignment += (30 * 4) + CDRBuffer.alignment(currentAlignment, (30 * 4)); // touch_sensor_readings_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // grip_stage_
      currentAlignment += (6 * 4) + CDRBuffer.alignment(currentAlignment, (6 * 4)); // goal_positions_
      currentAlignment += (6 * 4) + CDRBuffer.alignment(currentAlignment, (6 * 4)); // goal_velocities_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      for (int i = 0; i < actuator_positions_.length; ++i)
      {
         buffer.writeFloat(actuator_positions_[i]);
      }
      for (int i = 0; i < actuator_velocities_.length; ++i)
      {
         buffer.writeFloat(actuator_velocities_[i]);
      }
      for (int i = 0; i < actuator_currents_.length; ++i)
      {
         buffer.writeFloat(actuator_currents_[i]);
      }
      for (int i = 0; i < touch_sensor_readings_.length; ++i)
      {
         buffer.writeFloat(touch_sensor_readings_[i]);
      }
      buffer.writeInt(grip_stage_);
      for (int i = 0; i < goal_positions_.length; ++i)
      {
         buffer.writeFloat(goal_positions_[i]);
      }
      for (int i = 0; i < goal_velocities_.length; ++i)
      {
         buffer.writeFloat(goal_velocities_[i]);
      }

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      for (int i = 0; i < actuator_positions_.length; ++i)
      {
         actuator_positions_[i] = buffer.readFloat();
      }
      for (int i = 0; i < actuator_velocities_.length; ++i)
      {
         actuator_velocities_[i] = buffer.readFloat();
      }
      for (int i = 0; i < actuator_currents_.length; ++i)
      {
         actuator_currents_[i] = buffer.readFloat();
      }
      for (int i = 0; i < touch_sensor_readings_.length; ++i)
      {
         touch_sensor_readings_[i] = buffer.readFloat();
      }
      grip_stage_ = buffer.readInt();
      for (int i = 0; i < goal_positions_.length; ++i)
      {
         goal_positions_[i] = buffer.readFloat();
      }
      for (int i = 0; i < goal_velocities_.length; ++i)
      {
         goal_velocities_[i] = buffer.readFloat();
      }

   }

   @Override
   public void set(AbilityHandState from)
   {
      for (int i = 0; i < actuator_positions_.length; ++i)
      {
         actuator_positions_[i] = from.actuator_positions_[i];
      }
      for (int i = 0; i < actuator_velocities_.length; ++i)
      {
         actuator_velocities_[i] = from.actuator_velocities_[i];
      }
      for (int i = 0; i < actuator_currents_.length; ++i)
      {
         actuator_currents_[i] = from.actuator_currents_[i];
      }
      for (int i = 0; i < touch_sensor_readings_.length; ++i)
      {
         touch_sensor_readings_[i] = from.touch_sensor_readings_[i];
      }
      grip_stage_ = from.grip_stage_;
      for (int i = 0; i < goal_positions_.length; ++i)
      {
         goal_positions_[i] = from.goal_positions_[i];
      }
      for (int i = 0; i < goal_velocities_.length; ++i)
      {
         goal_velocities_[i] = from.goal_velocities_[i];
      }

   }

   public float[] getActuatorPositions()
   {
      return actuator_positions_;
   }

   public float[] getActuatorVelocities()
   {
      return actuator_velocities_;
   }

   public float[] getActuatorCurrents()
   {
      return actuator_currents_;
   }

   public float[] getTouchSensorReadings()
   {
      return touch_sensor_readings_;
   }

   public int getGripStage()
   {
      return grip_stage_;
   }

   public void setGripStage(int grip_stage_)
   {
      this.grip_stage_ = grip_stage_;
   }

   public float[] getGoalPositions()
   {
      return goal_positions_;
   }

   public float[] getGoalVelocities()
   {
      return goal_velocities_;
   }


   @Override
   public java.lang.String toString()
   {
      java.lang.StringBuilder builder = new java.lang.StringBuilder();
      builder.append("AbilityHandState {");
      builder.append("actuator_positions_=");
      builder.append(java.util.Arrays.toString(actuator_positions_));
      builder.append("actuator_velocities_=");
      builder.append(java.util.Arrays.toString(actuator_velocities_));
      builder.append("actuator_currents_=");
      builder.append(java.util.Arrays.toString(actuator_currents_));
      builder.append("touch_sensor_readings_=");
      builder.append(java.util.Arrays.toString(touch_sensor_readings_));
      builder.append("grip_stage_=");
      builder.append(grip_stage_);
      builder.append("goal_positions_=");
      builder.append(java.util.Arrays.toString(goal_positions_));
      builder.append("goal_velocities_=");
      builder.append(java.util.Arrays.toString(goal_velocities_));

      builder.append("}");
      return builder.toString();
   }
}