/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package ihmc_hands_ros2;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (ihmc_hands_ros2/AbilityHandCommand):
<pre>{@code
byte POSITION_CONTROL=0
byte VELOCITY_CONTROL=1
byte GRIP_CONTROL=2

# Specifies the control mode (ordinal of AbilityHandControlMode)
# Default = position control
byte control_mode 0

# Goal velocities when executing commands in velocity control mode
# Max velocities when in position or grip control modes
float32[6] goal_velocities

# Goal positions when using POSITION_CONTROL mode
float32[6] goal_positions

byte OPEN_GRIP=0
byte CLOSE_GRIP=1
byte PINCH_GRIP=2
byte FLAT_GRIP=3
byte HOOK_GRIP=4
byte RELAX_GRIP=5
byte DOOR_LEVER_OPEN_GRIP=6
byte DOOR_LEVER_CLOSE_GRIP=7
byte DOOR_LEVER_CRUSH_GRIP=8
byte KEY_OPEN_GRIP=9
byte KEY_CLOSE_GRIP=10

# Grip to execute in GRIP_CONTROL mode
byte grip
}</pre>
*/
public class AbilityHandCommand implements ROS2Message<AbilityHandCommand>
{
   public static final java.lang.String name = "ihmc_hands_ros2::msg::dds_::AbilityHandCommand_";

   public static final byte POSITION_CONTROL = 0;
   public static final byte VELOCITY_CONTROL = 1;
   public static final byte GRIP_CONTROL = 2;
   /**
      Specifies the control mode (ordinal of AbilityHandControlMode)
      Default = position control
   */
   private byte control_mode_;
   /**
      Goal velocities when executing commands in velocity control mode
      Max velocities when in position or grip control modes
   */
   private final float[] goal_velocities_;
   /**
      Goal positions when using POSITION_CONTROL mode
   */
   private final float[] goal_positions_;
   public static final byte OPEN_GRIP = 0;
   public static final byte CLOSE_GRIP = 1;
   public static final byte PINCH_GRIP = 2;
   public static final byte FLAT_GRIP = 3;
   public static final byte HOOK_GRIP = 4;
   public static final byte RELAX_GRIP = 5;
   public static final byte DOOR_LEVER_OPEN_GRIP = 6;
   public static final byte DOOR_LEVER_CLOSE_GRIP = 7;
   public static final byte DOOR_LEVER_CRUSH_GRIP = 8;
   public static final byte KEY_OPEN_GRIP = 9;
   public static final byte KEY_CLOSE_GRIP = 10;
   /**
      Grip to execute in GRIP_CONTROL mode
   */
   private byte grip_;

   public AbilityHandCommand()
   {
      control_mode_ = (byte) 0;
      goal_velocities_ = new float[6];
      goal_positions_ = new float[6];

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // control_mode_
      currentAlignment += (6 * 4) + CDRBuffer.alignment(currentAlignment, (6 * 4)); // goal_velocities_
      currentAlignment += (6 * 4) + CDRBuffer.alignment(currentAlignment, (6 * 4)); // goal_positions_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // grip_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeByte(control_mode_);
      for (int i = 0; i < goal_velocities_.length; ++i)
      {
         buffer.writeFloat(goal_velocities_[i]);
      }
      for (int i = 0; i < goal_positions_.length; ++i)
      {
         buffer.writeFloat(goal_positions_[i]);
      }
      buffer.writeByte(grip_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      control_mode_ = buffer.readByte();
      for (int i = 0; i < goal_velocities_.length; ++i)
      {
         goal_velocities_[i] = buffer.readFloat();
      }
      for (int i = 0; i < goal_positions_.length; ++i)
      {
         goal_positions_[i] = buffer.readFloat();
      }
      grip_ = buffer.readByte();

   }

   @Override
   public void set(AbilityHandCommand from)
   {
      control_mode_ = from.control_mode_;
      for (int i = 0; i < goal_velocities_.length; ++i)
      {
         goal_velocities_[i] = from.goal_velocities_[i];
      }
      for (int i = 0; i < goal_positions_.length; ++i)
      {
         goal_positions_[i] = from.goal_positions_[i];
      }
      grip_ = from.grip_;

   }

   public byte getControlMode()
   {
      return control_mode_;
   }

   public void setControlMode(byte control_mode_)
   {
      this.control_mode_ = control_mode_;
   }

   public float[] getGoalVelocities()
   {
      return goal_velocities_;
   }

   public float[] getGoalPositions()
   {
      return goal_positions_;
   }

   public byte getGrip()
   {
      return grip_;
   }

   public void setGrip(byte grip_)
   {
      this.grip_ = grip_;
   }


   @Override
   public java.lang.String toString()
   {
      java.lang.StringBuilder builder = new java.lang.StringBuilder();
      builder.append("AbilityHandCommand {");
      builder.append("POSITION_CONTROL=");
      builder.append(POSITION_CONTROL);
      builder.append("VELOCITY_CONTROL=");
      builder.append(VELOCITY_CONTROL);
      builder.append("GRIP_CONTROL=");
      builder.append(GRIP_CONTROL);
      builder.append("control_mode_=");
      builder.append(control_mode_);
      builder.append("goal_velocities_=");
      builder.append(java.util.Arrays.toString(goal_velocities_));
      builder.append("goal_positions_=");
      builder.append(java.util.Arrays.toString(goal_positions_));
      builder.append("OPEN_GRIP=");
      builder.append(OPEN_GRIP);
      builder.append("CLOSE_GRIP=");
      builder.append(CLOSE_GRIP);
      builder.append("PINCH_GRIP=");
      builder.append(PINCH_GRIP);
      builder.append("FLAT_GRIP=");
      builder.append(FLAT_GRIP);
      builder.append("HOOK_GRIP=");
      builder.append(HOOK_GRIP);
      builder.append("RELAX_GRIP=");
      builder.append(RELAX_GRIP);
      builder.append("DOOR_LEVER_OPEN_GRIP=");
      builder.append(DOOR_LEVER_OPEN_GRIP);
      builder.append("DOOR_LEVER_CLOSE_GRIP=");
      builder.append(DOOR_LEVER_CLOSE_GRIP);
      builder.append("DOOR_LEVER_CRUSH_GRIP=");
      builder.append(DOOR_LEVER_CRUSH_GRIP);
      builder.append("KEY_OPEN_GRIP=");
      builder.append(KEY_OPEN_GRIP);
      builder.append("KEY_CLOSE_GRIP=");
      builder.append(KEY_CLOSE_GRIP);
      builder.append("grip_=");
      builder.append(grip_);

      builder.append("}");
      return builder.toString();
   }
}