/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package ihmc_hands_ros2;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (ihmc_hands_ros2/EZGripperCommand):
<pre>{@code
byte POSITION_CONTROL=0
byte CALIBRATION=1
byte ERROR_RESET=2

# Specifies the desired operation mode.
byte operation_mode 255

# The temperature limit. Once reached, the gripper will go into cooldown mode
# until the actuator's temperature falls by 10% of the temperature limit.
# By default set to 75. It is not recommended going above 80.
# Automatic cooldown can be disabled by setting this value to 255.
uint8 temperature_limit 75

# The goal position
# 0.0 = fully closed, 1.0 = fully open
float32 goal_position

# Maximum effort to put into achieving the goal position
# 0.0 = no effort (fingers will not move), 1.0 = maximum effort (can quickly overheat actuator)
# 0.3 is a reasonable normal value, and it is recommended not to exceed 0.8.
float32 max_effort

# Keeping the torque off when not needed can help keep the gripper's temperature down
bool torque_on
}</pre>
*/
public class EZGripperCommand implements ROS2Message<EZGripperCommand>
{
   public static final java.lang.String name = "ihmc_hands_ros2::msg::dds_::EZGripperCommand_";

   public static final byte POSITION_CONTROL = 0;
   public static final byte CALIBRATION = 1;
   public static final byte ERROR_RESET = 2;
   /**
      Specifies the desired operation mode.
   */
   private byte operation_mode_;
   /**
      The temperature limit. Once reached, the gripper will go into cooldown mode
      until the actuator's temperature falls by 10% of the temperature limit.
      By default set to 75. It is not recommended going above 80.
      Automatic cooldown can be disabled by setting this value to 255.
   */
   private byte temperature_limit_;
   /**
      The goal position
      0.0 = fully closed, 1.0 = fully open
   */
   private float goal_position_;
   /**
      Maximum effort to put into achieving the goal position
      0.0 = no effort (fingers will not move), 1.0 = maximum effort (can quickly overheat actuator)
      0.3 is a reasonable normal value, and it is recommended not to exceed 0.8.
   */
   private float max_effort_;
   /**
      Keeping the torque off when not needed can help keep the gripper's temperature down
   */
   private boolean torque_on_;

   public EZGripperCommand()
   {
      operation_mode_ = (byte) 255;
      temperature_limit_ = (byte) 75;
      torque_on_ = (boolean) false;

   }

   public EZGripperCommand(EZGripperCommand from)
   {
      this();
      set(from);
   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // operation_mode_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // temperature_limit_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // goal_position_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // max_effort_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // torque_on_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeByte(operation_mode_);
      buffer.writeByte(temperature_limit_);
      buffer.writeFloat(goal_position_);
      buffer.writeFloat(max_effort_);
      buffer.writeBoolean(torque_on_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      operation_mode_ = buffer.readByte();
      temperature_limit_ = buffer.readByte();
      goal_position_ = buffer.readFloat();
      max_effort_ = buffer.readFloat();
      torque_on_ = buffer.readBoolean();

   }

   @Override
   public void set(EZGripperCommand from)
   {
      operation_mode_ = from.operation_mode_;
      temperature_limit_ = from.temperature_limit_;
      goal_position_ = from.goal_position_;
      max_effort_ = from.max_effort_;
      torque_on_ = from.torque_on_;

   }

   public byte getOperationMode()
   {
      return operation_mode_;
   }

   public void setOperationMode(byte operation_mode_)
   {
      this.operation_mode_ = operation_mode_;
   }

   public byte getTemperatureLimit()
   {
      return temperature_limit_;
   }

   public void setTemperatureLimit(byte temperature_limit_)
   {
      this.temperature_limit_ = temperature_limit_;
   }

   public float getGoalPosition()
   {
      return goal_position_;
   }

   public void setGoalPosition(float goal_position_)
   {
      this.goal_position_ = goal_position_;
   }

   public float getMaxEffort()
   {
      return max_effort_;
   }

   public void setMaxEffort(float max_effort_)
   {
      this.max_effort_ = max_effort_;
   }

   public boolean getTorqueOn()
   {
      return torque_on_;
   }

   public void setTorqueOn(boolean torque_on_)
   {
      this.torque_on_ = torque_on_;
   }


   @Override
   public java.lang.String toString()
   {
      java.lang.StringBuilder builder = new java.lang.StringBuilder();
      builder.append("EZGripperCommand {");
      builder.append("POSITION_CONTROL=");
      builder.append(POSITION_CONTROL);
      builder.append("CALIBRATION=");
      builder.append(CALIBRATION);
      builder.append("ERROR_RESET=");
      builder.append(ERROR_RESET);
      builder.append("operation_mode_=");
      builder.append(operation_mode_);
      builder.append("temperature_limit_=");
      builder.append(temperature_limit_);
      builder.append("goal_position_=");
      builder.append(goal_position_);
      builder.append("max_effort_=");
      builder.append(max_effort_);
      builder.append("torque_on_=");
      builder.append(torque_on_);

      builder.append("}");
      return builder.toString();
   }
}