/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package ihmc_hands_ros2;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (ihmc_hands_ros2/EZGripperState):
<pre>{@code
byte POSITION_CONTROL=0
byte CALIBRATION=1
byte ERROR_RESET=2
byte COOLDOWN=3

# Specifies the current operation mode.
byte operation_mode 255

# Temperature of the Dynamixel in Celsius
uint8 temperature

# The current Dynamixel position
# 0.0 = fully closed, 1.0 = fully open
float32 current_position

# The current amount of effort being used
# 0.0 = no effort, 1.0 = maximum effort
float32 current_effort

# Dynamixel's error code
# See: https://emanual.robotis.com/docs/en/dxl/protocol1/#error
uint8 error_code

# Realtime tick of the Dynamixel
# If this value isn't changing, communication with the gripper is broken
int32 realtime_tick

# Whether the hand has been calibrated
bool is_calibrated
}</pre>
*/
public class EZGripperState implements ROS2Message<EZGripperState>
{
   public static final java.lang.String name = "ihmc_hands_ros2::msg::dds_::EZGripperState_";

   public static final byte POSITION_CONTROL = 0;
   public static final byte CALIBRATION = 1;
   public static final byte ERROR_RESET = 2;
   public static final byte COOLDOWN = 3;
   /**
      Specifies the current operation mode.
   */
   private byte operation_mode_;
   /**
      Temperature of the Dynamixel in Celsius
   */
   private byte temperature_;
   /**
      The current Dynamixel position
      0.0 = fully closed, 1.0 = fully open
   */
   private float current_position_;
   /**
      The current amount of effort being used
      0.0 = no effort, 1.0 = maximum effort
   */
   private float current_effort_;
   /**
      Dynamixel's error code
      See: https://emanual.robotis.com/docs/en/dxl/protocol1/#error
   */
   private byte error_code_;
   /**
      Realtime tick of the Dynamixel
      If this value isn't changing, communication with the gripper is broken
   */
   private int realtime_tick_;
   /**
      Whether the hand has been calibrated
   */
   private boolean is_calibrated_;

   public EZGripperState()
   {
      operation_mode_ = (byte) 255;
      is_calibrated_ = (boolean) false;

   }

   public EZGripperState(EZGripperState from)
   {
      this();
      set(from);
   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // operation_mode_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // temperature_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // current_position_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // current_effort_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // error_code_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // realtime_tick_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // is_calibrated_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeByte(operation_mode_);
      buffer.writeByte(temperature_);
      buffer.writeFloat(current_position_);
      buffer.writeFloat(current_effort_);
      buffer.writeByte(error_code_);
      buffer.writeInt(realtime_tick_);
      buffer.writeBoolean(is_calibrated_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      operation_mode_ = buffer.readByte();
      temperature_ = buffer.readByte();
      current_position_ = buffer.readFloat();
      current_effort_ = buffer.readFloat();
      error_code_ = buffer.readByte();
      realtime_tick_ = buffer.readInt();
      is_calibrated_ = buffer.readBoolean();

   }

   @Override
   public void set(EZGripperState from)
   {
      operation_mode_ = from.operation_mode_;
      temperature_ = from.temperature_;
      current_position_ = from.current_position_;
      current_effort_ = from.current_effort_;
      error_code_ = from.error_code_;
      realtime_tick_ = from.realtime_tick_;
      is_calibrated_ = from.is_calibrated_;

   }

   public byte getOperationMode()
   {
      return operation_mode_;
   }

   public void setOperationMode(byte operation_mode_)
   {
      this.operation_mode_ = operation_mode_;
   }

   public byte getTemperature()
   {
      return temperature_;
   }

   public void setTemperature(byte temperature_)
   {
      this.temperature_ = temperature_;
   }

   public float getCurrentPosition()
   {
      return current_position_;
   }

   public void setCurrentPosition(float current_position_)
   {
      this.current_position_ = current_position_;
   }

   public float getCurrentEffort()
   {
      return current_effort_;
   }

   public void setCurrentEffort(float current_effort_)
   {
      this.current_effort_ = current_effort_;
   }

   public byte getErrorCode()
   {
      return error_code_;
   }

   public void setErrorCode(byte error_code_)
   {
      this.error_code_ = error_code_;
   }

   public int getRealtimeTick()
   {
      return realtime_tick_;
   }

   public void setRealtimeTick(int realtime_tick_)
   {
      this.realtime_tick_ = realtime_tick_;
   }

   public boolean getIsCalibrated()
   {
      return is_calibrated_;
   }

   public void setIsCalibrated(boolean is_calibrated_)
   {
      this.is_calibrated_ = is_calibrated_;
   }


   @Override
   public java.lang.String toString()
   {
      java.lang.StringBuilder builder = new java.lang.StringBuilder();
      builder.append("EZGripperState {");
      builder.append("POSITION_CONTROL=");
      builder.append(POSITION_CONTROL);
      builder.append("CALIBRATION=");
      builder.append(CALIBRATION);
      builder.append("ERROR_RESET=");
      builder.append(ERROR_RESET);
      builder.append("COOLDOWN=");
      builder.append(COOLDOWN);
      builder.append("operation_mode_=");
      builder.append(operation_mode_);
      builder.append("temperature_=");
      builder.append(temperature_);
      builder.append("current_position_=");
      builder.append(current_position_);
      builder.append("current_effort_=");
      builder.append(current_effort_);
      builder.append("error_code_=");
      builder.append(error_code_);
      builder.append("realtime_tick_=");
      builder.append(realtime_tick_);
      builder.append("is_calibrated_=");
      builder.append(is_calibrated_);

      builder.append("}");
      return builder.toString();
   }
}