#ifndef __ihmc_hands_ros2__msg__AbilityHandState__idl__
#define __ihmc_hands_ros2__msg__AbilityHandState__idl__

module ihmc_hands_ros2
{
  module msg
  {
    module dds
    {
      const octet LEFT =
      0;

      const octet RIGHT =
      1;


      @TypeCode(type="ihmc_hands_ros2::msg::dds_::AbilityHandState_")
      struct AbilityHandState
      {
        /**
         * The hand's serial number. E.g. 24ABH265
         */
        string<32> identifier;
        /**
         * Specifies whether the hand is a left or right hand
         */
        @defaultValue(value=255)
        octet hand_side;
        /**
         * The actuator positions in degrees
         */
        float actuator_positions[6];
        /**
         * The current finger velocities (deg/sec)
         */
        float actuator_velocities[6];
        /**
         * The actuator currents in amps
         */
        float actuator_currents[6];
        /**
         * The touch sensor pressure readings in Newtons
         */
        float touch_sensor_readings[30];
        /**
         * If grip control mode, the current grip stage
         */
        long grip_stage;
        /**
         * The goal positions in degrees
         */
        float goal_positions[6];
        /**
         * The goal or max velocities (deg/sec)
         */
        float goal_velocities[6];
      };
    };
  };
};

#endif
