#ifndef __ihmc_hands_ros2__msg__AbilityHandCommand__idl__
#define __ihmc_hands_ros2__msg__AbilityHandCommand__idl__

module ihmc_hands_ros2
{
  module msg
  {
    module dds
    {
      const octet POSITION_CONTROL =
      0;

      const octet VELOCITY_CONTROL =
      1;

      const octet GRIP_CONTROL =
      2;

      const octet OPEN_GRIP =
      0;

      const octet CLOSE_GRIP =
      1;

      const octet PINCH_GRIP =
      2;

      const octet FLAT_GRIP =
      3;

      const octet HOOK_GRIP =
      4;

      const octet RELAX_GRIP =
      5;

      const octet DOOR_LEVER_OPEN_GRIP =
      6;

      const octet DOOR_LEVER_CLOSE_GRIP =
      7;

      const octet DOOR_LEVER_CRUSH_GRIP =
      8;

      const octet KEY_OPEN_GRIP =
      9;

      const octet KEY_CLOSE_GRIP =
      10;


      @TypeCode(type="ihmc_hands_ros2::msg::dds_::AbilityHandCommand_")
      struct AbilityHandCommand
      {
        /**
         * The hand's serial number. E.g. 24ABH265
         */
        string<32> identifier;
        /**
         * Specifies the control mode (ordinal of AbilityHandControlMode)
         * Default = position control
         */
        octet control_mode;
        /**
         * Goal velocities when executing commands in velocity control mode
         * Max velocities when in position or grip control modes
         */
        float goal_velocities[6];
        /**
         * Goal positions when using POSITION_CONTROL mode
         */
        float goal_positions[6];
        /**
         * Grip to execute in GRIP_CONTROL mode
         */
        octet grip;
      };
    };
  };
};

#endif
